//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GeneThon.rc
//
#define IDR_MAINFRAME                   2
#define IDR_GENEDOTYPE                  3
#define IDS_DUPSEQNAME                  4
#define IDR_SUMMARYVIEW                 5
#define IDR_TEXTVIEW                    6
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_POS                101
#define IDD_CONFDISPLAY                 108
#define IDD_SEQDIALOG                   112
#define IDD_SEQDETAILS                  114
#define IDD_CONFPRINT                   126
#define IDD_COLORBAR                    134
#define IDB_GENEBAR                     143
#define IDB_GENETHON                    144
#define IDB_SMALLLOGO                   145
#define IDD_GRAPHSETUP                  156
#define IDD_IMPORTTYPE                  166
#define IDB_INLOVE                      167
#define IDD_EXPORTDLG                   177
#define IDD_SELARRSEQ                   186
#define IDD_GENBANK                     191
#define IDB_BITMAP1                     193
#define IDC_PAGEWIDTH                   1003
#define IDC_PAGEHEIGHT                  1004
#define IDC_CHGFONT                     1005
#define IDC_FONTWEIGHT                  1007
#define IDC_XBORDERPCT                  1007
#define IDC_XAXISTITLEPCT               1009
#define IDC_YBORDERPCT                  1010
#define IDC_CHARTTITLE                  1015
#define IDC_YAXISTITLE                  1016
#define IDC_XAXISTITLE                  1017
#define IDC_YAXISTITLEPCT               1018
#define IDC_CHARTTITLEPCT               1019
#define IDC_LINEWIDTH                   1020
#define IDC_XAXISROUNDING               1021
#define IDC_LEFTBORDER                  1023
#define IDC_RIGHTBORDER                 1024
#define IDC_TOPBORDER                   1025
#define IDC_BOTTOMBORDER                1026
#define IDC_EDITWIDTH                   1027
#define IDC_GENEFIXEDWIDTH              1028
#define IDC_GENEAUTOWIDTH               1029
#define IDC_LIST1                       1044
#define IDC_SEQMOVEUP                   1045
#define IDC_SEQMOVEDOWN                 1046
#define IDC_SEQDELETE                   1047
#define IDC_SEQIMPORT                   1048
#define IDC_SEQDETAILS                  1049
#define IDC_SEQDETNAME                  1050
#define IDC_CONSENSUSLINE               1051
#define IDC_CONSENSUSBELOW              1052
#define IDC_CONSENSUSNONE               1053
#define IDC_SEQINDON                    1061
#define IDC_SEQINDOFF                   1062
#define IDC_ORPORT                      1063
#define IDC_ORLAND                      1064
#define IDC_MOVETOP                     1113
#define IDC_PICTWIDTH                   1119
#define IDC_PICTHEIGHT                  1120
#define IDC_PICTASCENT                  1121
#define IDC_EDITFONTPOINTS              1149
#define IDC_DISP                        1159
#define IDC_PRINTPAGE0                  1185
#define IDC_PRINTPAGE1                  1186
#define IDC_PRINTPAGE2                  1187
#define IDC_PRINTPAGE3                  1188
#define IDC_PRINTPAGE4                  1189
#define IDC_PRINTSTRINGFLAG1            1190
#define IDC_PRINTSTRINGFLAG2            1191
#define IDC_PRINTSTRINGFLAG0            1192
#define IDC_PRINTFONTNAME               1193
#define IDC_PRINTFONTPOINTS             1194
#define IDC_PRINTFONTWEIGHT             1195
#define IDC_PRINTPAGEOFFSET             1196
#define IDC_PRINTSTRING                 1197
#define IDC_CHANGEPRINTFONT             1198
#define IDC_GENEBLOCKPOS0               1199
#define IDC_GENEBLOCKPOS1               1200
#define IDC_GENEBLOCKPOS2               1201
#define IDC_MOVEBOTT                    1202
#define IDC_SEQEXPORT                   1205
#define IDC_INPUT                       1251
#define IDC_INSTRUCT                    1262
#define IDC_IMPORTTYPE0                 1301
#define IDC_IMPORTTYPE2                 1302
#define IDC_IMPORTTYPE3                 1303
#define IDC_IMPORTTYPE4                 1304
#define IDC_IMPORTTYPE5                 1305
#define IDC_NAMESEP                     1325
#define IDC_INDSEP                      1326
#define IDC_MAXNAME                     1327
#define IDC_PRINTSHADE                  1387
#define IDC_LISTSEQUENCE                1418
#define IDC_TEXTSTART                   1427
#define IDC_SUMCOLINCH                  1432
#define IDC_SUMCOLINCHDIS               1433
#define IDC_COL2WID11                   1434
#define IDC_SUM2COL02                   1435
#define IDC_SUMDEFDIS                   1436
#define IDC_SUMTEXTBLACK                1437
#define IDC_FILE                        1438
#define IDC_CLIP                        1439
#define IDC_IMPORTTYPE6                 1440
#define IDIMPORT                        1441
#define IDEXPORT                        1442
#define IDC_TEXTNOGAP                   1444
#define IDC_EXPORTTYPE                  1445
#define IDC_SELALLSEQ                   1446
#define IDC_SELLISTSEQ                  1447
#define IDC_DESCR                       1476
#define IDC_SEQCOUNT                    1480
#define IDC_IMPORTTYPE7                 1482
#define IDC_EXNT                        1483
#define IDC_IUPAC                       1484
#define IDC_PRINTDATE                   1485
#define IDC_PRINTFILENAME               1486
#define IDC_GENEALIGNWIDTH              1493
#define IDC_SHOWMANSHADE                1494
#define IDC_SHOWCOMMENTS                1495
#define IDC_DESEL                       1498
#define IDC_COMPLEMENT                  1499
#define IDC_SORTDESC                    1533
#define IDC_GENBANK                     1535
#define IDC_LOCUS                       1536
#define IDC_ACCESSION                   1537
#define IDC_NID                         1538
#define IDC_TRANSLATION                 1539
#define IDC_ORIGIN                      1540
#define IDC_MAKEBACKUPS                 1555
#define IDC_SORTNAME                    1556
#define IDC_SAVESORT                    1557
#define IDC_LOADSORT                    1558
#define IDC_LOCAFTERSEQ                 1559
#define IDC_LOCAFTERNAME                1560
#define IDC_COUNTSEL                    1562
#define IDC_PID                         1564
#define IDC_MFCCOLORBUTTON1             1567
#define IDC_MFCCOLORBUTTON2             1568
#define ID_EDIT_COPYINV                 32779
#define IDM_CONFIGURE                   32780
#define IDM_GENEARRANGE                 32782
#define IDM_SELECT                      32787
#define IDM_GENEINSERTDASH              32794
#define IDM_GENEDELETEDASH              32795
#define IDM_GENECLEARSHADE              32796
#define IDM_SELECTCOL                   32801
#define IDM_GENECREATEWIN               32802
#define IDM_GENEEDITSEQ                 32806
#define IDM_GENEINSERTOTHER             32809
#define IDM_GENEDELETEOTHER             32810
#define IDM_GENEDELETEFILL              32814
#define IDM_GENEINSERTFILL              32815
#define ID_ON_HELP                      32817
#define IDM_GENESAVEINI                 32822
#define IDM_GENELOADINI                 32823
#define IDM_TITLINGF                    32827
#define IDM_MANUALSHADE                 32828
#define ID_EDIT_COPY8                   32829
#define ID_EDIT_COPY0                   32830
#define ID_EDIT_COPYINV0                32832
#define ID_EDIT_COPYINV8                32834
#define ID_EDIT_COPYBIT                 32835
#define ID_EDIT_COPYINVBIT              32836
#define IDM_GENEVIEW                    32842
#define IDM_COPYTEXT                    32851
#define IDM_GENECOPYPICT                32852
#define IDM_GENEEDITMODE                32853
#define IDM_COPYMETACLIP                32872
#define IDM_COPYMETAFILE                32873
#define IDM_GRAPHSETUP                  32887
#define IDM_FILEEXPORT                  32897
#define IDM_FILEIMPORT                  32898
#define IDM_CLEARGAPCOLS                32899
#define IDM_GENEFINDREPLACE             32904
#define IDM_GENECOPYSEQ                 32905
#define IDM_GENECOPYHTML                32919
#define IDM_GENESCOREKEY                32921
#define IDM_STCLOADPDB                  32926
#define IDM_SUMMARYVIEW                 32927
#define IDM_GENECOPYRTF                 32928
#define IDM_GENEMOVE                    32932
#define IDM_DELCOLUMNS                  32933
#define IDM_FIND                        32935
#define IDM_COPYCONS                    32938
#define IDM_SHOWMANSHADE                32939
#define IDM_SHOWCOMMENTS                32940
#define IDM_CLEARMANSHADE               32941
#define IDM_CLEARCOMMENTS               32942
#define IDM_SELECTARRSEQ                32943
#define IDM_COMPLIMENTSEL               32952
#define IDM_REPLACEFROMPROJ             32954
#define IDM_GENEINSERTONE               32957
#define IDM_GENEDELETEONE               32959
#define IDM_GENEREPORTVIEW              32960
#define IDM_DNAFFREQREP                 32961
#define IDM_REPSAVEFILE                 32962
#define IDM_ALIGN                       32968
#define IDM_MANSHADEREP                 32969
#define IDM_SHADING_REP                 32970
#define IDM_CONFIGREPORT                32972
#define IDM_CONSPROSITE                 32973
#define IDS_SEQDELSEQ                   57645
#define IDS_NOMOREPAGES                 57646
#define IDS_DISPLAYMAX                  57647
#define IDS_NEWFAILED                   57654
#define IDS_EXCEPTION                   57655

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32974
#define _APS_NEXT_CONTROL_VALUE         1571
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
